// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/reels": {
    params: {};
  };
  "/tagged": {
    params: {};
  };
  "/highlights": {
    params: {};
  };
  "/search": {
    params: {};
  };
  "/create": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/profile/posts/grid": {
    params: {};
  };
  "/profile/reels/grid": {
    params: {};
  };
  "/profile/tagged/grid": {
    params: {};
  };
  "/profile/highlights": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/reels" | "/tagged" | "/highlights" | "/search" | "/create" | "/profile" | "/profile/posts/grid" | "/profile/reels/grid" | "/profile/tagged/grid" | "/profile/highlights";
  };
  "routes/_layout.tsx": {
    id: "routes/_layout";
    page: "/" | "/reels" | "/tagged" | "/highlights" | "/search" | "/create" | "/profile" | "/profile/posts/grid" | "/profile/reels/grid" | "/profile/tagged/grid" | "/profile/highlights";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/reels.tsx": {
    id: "routes/reels";
    page: "/reels";
  };
  "routes/tagged.tsx": {
    id: "routes/tagged";
    page: "/tagged";
  };
  "routes/highlights.tsx": {
    id: "routes/highlights";
    page: "/highlights";
  };
  "routes/search.tsx": {
    id: "routes/search";
    page: "/search";
  };
  "routes/create.tsx": {
    id: "routes/create";
    page: "/create";
  };
  "routes/profile.tsx": {
    id: "routes/profile";
    page: "/profile";
  };
  "routes/profile.posts.grid.tsx": {
    id: "routes/profile.posts.grid";
    page: "/profile/posts/grid";
  };
  "routes/profile.reels.grid.tsx": {
    id: "routes/profile.reels.grid";
    page: "/profile/reels/grid";
  };
  "routes/profile.tagged.grid.tsx": {
    id: "routes/profile.tagged.grid";
    page: "/profile/tagged/grid";
  };
  "routes/profile.highlights.tsx": {
    id: "routes/profile.highlights";
    page: "/profile/highlights";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_layout": typeof import("./app/routes/_layout.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/reels": typeof import("./app/routes/reels.tsx");
  "routes/tagged": typeof import("./app/routes/tagged.tsx");
  "routes/highlights": typeof import("./app/routes/highlights.tsx");
  "routes/search": typeof import("./app/routes/search.tsx");
  "routes/create": typeof import("./app/routes/create.tsx");
  "routes/profile": typeof import("./app/routes/profile.tsx");
  "routes/profile.posts.grid": typeof import("./app/routes/profile.posts.grid.tsx");
  "routes/profile.reels.grid": typeof import("./app/routes/profile.reels.grid.tsx");
  "routes/profile.tagged.grid": typeof import("./app/routes/profile.tagged.grid.tsx");
  "routes/profile.highlights": typeof import("./app/routes/profile.highlights.tsx");
};